### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by szaghi** [azag0/fcompile#1]
Dear @azag0 

Thank you very much for sharing your work, it is appreciated.

I am working on a similar project, [FoBiS](https://github.com/szaghi/FoBiS), maybe can interest to collaborate.

I am going to study your tool, thank you again!

My best regards.

**Comment by jhrmnn** [comment]
Hello. I'm happy to hear you like fcompile. Looking at your project though, it has probably much more functionality than mine!

**Comment by szaghi** [comment]
FoBiS is simply older, your will grow with time. I am study your parallel approach, it is interesting.

See you soon.

**Comment by jhrmnn** [comment]
The prioritization of compilation tasks is one thing I spent some time figuring out. On the project with ~1500 source files, for which I originally wrote this tool, it can reach parallelization of about 16, at which point the total build time is determined by the longest direct dependency chain.
